laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('form');
});
Route::post('submitForm','MuridController@indexDT');
Route::get('/downloadPDF/{id}','MuridController@downloadPDF');

Route::get('/', ['uses' => 'PresensiController@index', 'as' => 'presensi']);
Route::post('/presensi/post', ['uses' => 'PresensiController@presensi', 'as' => 'presensi-post']);
Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', ['uses' => 'IndexController@index', 'as' => 'dashboard']);


    Route::resource('riwayat', 'RiwayatController');
    Route::resource('murid', 'MuridController');
    Route::resource('kelas', 'KelasController');
    Route::resource('sesi-kelas', 'SesiKelasController');
    Route::resource('poin', 'PoinController');
    Route::get('bulk-add', 'MuridController@bulkAdd')->name('bulk');
    Route::post('bulk-add', 'MuridController@bulkAddPost')->name('bulk');
    Route::get('dt-murid', 'MuridController@indexDT')->name('dt-murid');
    Route::delete('/murid/{id}', 'MuridController@destroy')->name('murid.destroy');
    Route::delete('dl-murid', 'MuridController@destroy')->name('dl-murid');
    Route::get('murid/{id}/delete', ['uses' => 'MuridController@destroy', 'as' => 'murid.delete']);
    Route::get('dt-kelas', 'KelasController@kelasDT')->name('dt-kelas');
    Route::get('dt-riwayat', 'RiwayatController@kelasDT')->name('dt-riwayat');
    Route::get('r-murid', 'MuridController@rDT')->name('r-murid');
    Route::get('dt-sesi', 'SesiKelasController@sesiDT')->name('dt-sesi');
    Route::get('dt-poin-history/{id}', 'PoinController@poinHistoryDT')->name('dt-poin-history');
    Route::post('dz-upload', 'MuridController@dropZoneUpload')->name('dz-upload');
});

Route::get('Murid', function(MuridDataTable $dataTable) {
    return $dataTable->render('murid.index');
});


Route::get('debugging', function () {
    /* $date = \Carbon\Carbon::now()->setTimezone('Asia/Jakarta');
     $sesi = \App\SesiKelas::all();
     $now = $date->format('Y-m-d H:i:s');
     $day = $date->format('l');

     $output = array();
     foreach ($sesi as $sesi_kelas) {
         $start = \Carbon\Carbon::parse($sesi_kelas->jam_mulai)->format('Y-m-d H:i:s');
         $end = \Carbon\Carbon::parse($sesi_kelas->jam_selesai)->format('Y-m-d H:i:s');

         //cek sesi kelas
         if ($now > $start && $now < $end) {
             //cek murid sudah pernah absen pada sesi kelas
             $new_presensi = \App\Presensi::where('murid_id', '=', 22)->whereBetween('created_at', [$start, $end])->first();
             //dd($new_presensi->created_at);

             $presensi_exist_time = $new_presensi['created_at'];
             //dd($presensi_exist_time);
             if ($new_presensi !== null && $presensi_exist_time > $start && $presensi_exist_time < $end) {
                 $output = array();
                 $output = array(['type' => 'warning', 'message' => $new_presensi->murid->nama_lengkap . ' Telah melakukan presensi pada sesi kelas saat ini']);
             } else {

                 $output = array();
                 $output = array(['type' => 'success', 'message' => 'Berhasil melakukan presensi']);
                 break;
             }
         } else {
             $output = array(['type' => 'error', 'message' => 'Tidak ada kelas yg aktif pada saat ini']);
         }
     }
     return response()->json($output);*/
    $user = new \App\User();
    $user->name = 'Administrator';
    $user->username = 'administrator';
    $user->email = 'admin@presensi.com';
    $user->password = bcrypt('123456');
    $user->save();
    dd($user);

});
Auth::routes();

laravel/resources/views/kelas.1/_form.blade.php
<h5 class="form-header">Data Kelas</h5>
<div class="form-desc">Form dengan tanda <span class="text-danger">*</span> harus di isi.
</div>
<div class="form-group">
    <label for=""> Nama Kelas <span class="text-danger">*</span></label>
    <input class="form-control" data-error="Nama kelas harus di isi"
           placeholder="Masukkan nama lengkap" required="required" name="nama_kelas" type="text"
           value="{{ @$kelas->nama_kelas }}">
    <div class="help-block form-text with-errors form-control-feedback"></div>
</div>
<div class="form-group">
    <label for=""> Deskripsi <span class="text-danger">*</span></label>
    <input class="form-control" data-error="Deskripsi kelas harus di isi"
           placeholder="Masukkan nama panggilan" required name="deskripsi" type="text" value="{{ @$kelas->deskripsi }}">
    <div class="help-block form-text with-errors form-control-feedback"></div>
</div>

{{ csrf_field() }}
<div class="form-buttons-w">
    <button class="btn btn-primary" type="submit"> Simpan</button>

    <!-- hapus -->
    
</div>


  

laravel/resources/views/kelas.1/create.blade.php
@extends('layout.master')

@section('title')
    <title>Tambah Kelas - Admin</title>
@stop

@section('content-box')
    <div class="row">
        <div class="col-sm-12">
            <div class="element-wrapper">
                <div class="element-box">
                    <form id="formValidate" method="post" action="{{ route('kelas.store') }}">
                        @include('kelas._form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('content-panel')
    <div class="content-panel">

    </div>
@endsection

@section('script')
    <script>

    </script>
@endsection

laravel/resources/views/kelas.1/edit.blade.php
@extends('layout.master')

@section('title')
    <title>Edit Kelas {{ ucwords(strtolower($kelas->nama_kelas)) }} - Member</title>
@stop

@section('content-box')
    <div class="row">
        <div class="col-sm-12">
            <div class="element-wrapper">
                <div class="element-box">
                    <form id="formValidate" method="post" action="{{ route('kelas.update', $kelas->id) }}">
                        @include('kelas._form')
                        {{ method_field('PUT') }}
                        <br>
                        
                        <form method="POST" action="{{ route('kelas.destroy', [$kelas->id]) }}">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}                    
                        <button class="btn btn-warning" type="submit"> Hapus</button>
                      </form>
                      
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('content-panel')
    <div class="content-panel">

    </div>
@endsection

@section('script')
    <script>
        $(function () {
            $('div#dz-upload').addClass('dropzone').dropzone({
                url: "{{ route('dz-upload') }}",
                method: "post",
                uploadMultiple: false,
                maxFiles: 1,
                acceptedFiles: "image/*",
                init: function () {
                    var myDropzone = this;
                    var mockFile = {name: "Filename", size: 0};
                    myDropzone.emit("addedfile", mockFile);
                    myDropzone.emit("thumbnail", mockFile, "{{ asset('storage/'.@$murid->foto) }}");
                    myDropzone.files.push(mockFile);
                    myDropzone.emit("complete", mockFile);
                    console.log(myDropzone.files.length);
                    this.on("sending", function (file, xhr, formData) {
                        formData.append("_token", '{{ csrf_token() }}');
                    });
                    this.on("success", function (files, response) {
                        this.removeFile(mockFile);
                        $('#foto').val(response);
                        console.log(response);
                    });

                }
            })
        });

    </script>
@endsection

laravel/resources/views/kelas.1/index.blade.php
@extends('layout.master')

@section('title')
    <title>Daftar Kelas - Admin</title>
@stop

@section('content-box')
    <div class="element-wrapper">
        <h6 class="element-header">Kelas</h6>
        <div class="element-box">
            <h5 class="form-header">Daftar Kelas</h5>
            <div class="form-desc">Berisi data kelas yang ada
            </div>
            <div class="controls-above-table">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-inline justify-content-sm-end">
                            <a class="btn btn-primary" href="{{ route('kelas.create') }}">Tambah</a>
                            <div aria-hidden="true" aria-labelledby="exampleModalLabel" class="modal fade"
                                 id="exampleModal1" role="dialog" tabindex="-1">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                            <button aria-label="Close" class="close" data-dismiss="modal"
                                                    type="button">
                                                <span aria-hidden="true"> &times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <form>
                                                <div class="form-group">
                                                    <label for=""> Email address</label>
                                                    <input class="form-control" placeholder="Enter email"
                                                           type="email">
                                                </div>
                                                <div class="row">
                                                    <div class="col-sm-6">
                                                        <div class="form-group">
                                                            <label for=""> Password</label>
                                                            <input class="form-control" placeholder="Password"
                                                                   type="password">
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-6">
                                                        <div class="form-group">
                                                            <label for="">Confirm Password</label>
                                                            <input class="form-control" placeholder="Password"
                                                                   type="password">
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                        <div class="modal-footer">
                                            <button class="btn btn-secondary" data-dismiss="modal" type="button">
                                                Close
                                            </button>
                                            <button class="btn btn-primary" type="button"> Save changes</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table id="tabel-kelas" width="100%" class="table table-hover table-striped table-lightfont">
                    <thead>
                    <tr>
                        <th>ID#</th>
                        <th>Nama Kelas</th>
                        <th>Keterangan</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>ID#</th>
                        <th>Nama Kelas</th>
                        <th>Keterangan</th>
                        <th>Action</th>
                    </tr>
                    </tfoot>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $(function () {
            $('#tabel-kelas').css('text-transform', 'lowercase').DataTable({
                pagingType: "simple_numbers",
                paging: true,
                pageLength: 25,
                order: [[0, "asc"]],
                processing: true,
                serverSide: true,
                ajax: '{{ route('dt-kelas') }}',
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'nama_kelas', name: 'nama_kelas'},
                    {data: 'deskripsi', name: 'deskripsi'},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ]
            });
        });

    </script>
@endsection

laravel/resources/views/kelas.1/show.blade.php
@extends('layout.master')

@section('title')
    <title>{{ ucwords(strtolower($murid->nama_lengkap)) }} - Murid - Admin</title>
@stop

@section('content-box')
    <div class="element-wrapper">
        <div class="user-profile">
            <div class="up-head-w" style="background-image:url({{ asset('img/profile-cover.jpg') }})">
                <div class="up-social">
                    <a href="{{ route('murid.edit',$murid->id) }}">
                        <i class="os-icon os-icon-edit-1"></i>
                    </a>

                </div>
                <div class="up-main-info">
                    <div class="user-avatar-w">
                        <div class="user-avatar">
                            <img alt="" src="{{ asset($murid->foto) }}">
                        </div>
                    </div>
                    <h1 class="up-header">{{ ucwords(strtolower($murid->nama_lengkap)) }}</h1>
                    <h5 class="up-sub-header">{{ ucwords(strtolower($murid->nama_panggilan)) }},
                        Kelas {{ $murid->kelas->nama_kelas }}</h5>
                </div>
                <svg class="decor" width="842px" height="219px" viewBox="0 0 842 219"
                     preserveAspectRatio="xMaxYMax meet"
                     version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                    <g transform="translate(-381.000000, -362.000000)" fill="#FFFFFF">
                        <path class="decor-path"
                              d="M1223,362 L1223,581 L381,581 C868.912802,575.666667 1149.57947,502.666667 1223,362 Z"></path>
                    </g>
                </svg>
            </div>
            <div class="up-controls">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="value-pair">
                            <div class="label">Usia:</div>
                            <div class="value">{{ \Carbon\Carbon::parse($murid->tanggal_lahir)->age }} tahun.</div>
                        </div>
                        <div class="value-pair">
                            <div class="label">Gender:</div>
                            <div class="value">{{ ($murid->gender=='L'? 'Laki-laki':'Perempuan') }}</div>
                        </div>
                    </div>
                    <div class="col-lg-6 text-right">
                        @php($telp = explode(',',$murid->no_telepon))
                        @foreach($telp as $item)
                            <a class="btn btn-secondary btn-sm" href="tel:{{ $item }}">
                                <i class="os-icon os-icon-email-forward"></i>
                                <span>{{ $item }}</span>
                            </a>
                        @endforeach

                    </div>
                </div>
            </div>
            <div class="up-contents">
                <h5 class="element-header">Profile Info</h5>
                <div class="row m-b">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-sm-6 b-r b-b">
                                <div class="el-tablo centered padded">
                                    <div class="value">{{ ucwords(strtolower($murid->nama_ayah)) }}</div>
                                    <div class="label">Nama Ayah</div>
                                </div>
                            </div>
                            <div class="col-sm-6 b-b b-r">
                                <div class="el-tablo centered padded">
                                    <div class="value">{{ ucwords(strtolower($murid->nama_ibu)) }}</div>
                                    <div class="label">Nama Ibu</div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6 b-r">
                                <div class="el-tablo centered padded">
                                    <div class="value">{{ ucwords(strtolower($murid->alamat)) }}</div>
                                    <div class="label">Alamat</div>
                                </div>
                            </div>
                            <div class="col-sm-6 b-r">
                                <div class="el-tablo centered padded">
                                    <div class="value">{{ ucwords(strtolower($murid->tempat_lahir)) }}
                                        <br>{{ \Carbon\Carbon::parse($murid->tanggal_lahir)->toFormattedDateString() }}
                                    </div>
                                    <div class="label">Tempat/Tanggal Lahir</div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="os-tabs-w">
                    <div class="os-tabs-controls">
                        <ul class="nav nav-tabs bigger">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#tab_overview">Activity</a>
                            </li>
                        </ul>
                        <ul class="nav nav-pills smaller d-none d-md-flex">
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#">Bulan ini</a>
                            </li>
                        </ul>
                    </div>
                    <div class="tab-content">
                        <div class="tab-pane active" id="tab_overview">
                            <div class="timed-activities padded">
                                <div class="timed-activity">
                                    <div class="ta-date">
                                        <span>21st Jan, 2017</span>
                                    </div>
                                    <div class="ta-record-w">
                                        <div class="ta-record">
                                            <div class="ta-timestamp">
                                                <strong>11:55</strong> am
                                            </div>
                                            <div class="ta-activity">Created a post called
                                                <a href="#">Register new symbol</a> in Rogue
                                            </div>
                                        </div>
                                        <div class="ta-record">
                                            <div class="ta-timestamp">
                                                <strong>2:34</strong> pm
                                            </div>
                                            <div class="ta-activity">Commented on story
                                                <a href="#">How to be a leader</a> in
                                                <a href="#">Financial</a> category
                                            </div>
                                        </div>
                                        <div class="ta-record">
                                            <div class="ta-timestamp">
                                                <strong>7:12</strong> pm
                                            </div>
                                            <div class="ta-activity">Added
                                                <a href="#">John Silver</a> as a friend
                                            </div>
                                        </div>
                                        <div class="ta-record">
                                            <div class="ta-timestamp">
                                                <strong>9:39</strong> pm
                                            </div>
                                            <div class="ta-activity">Started following user
                                                <a href="#">Ben Mosley</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="timed-activity">
                                    <div class="ta-date">
                                        <span>3rd Feb, 2017</span>
                                    </div>
                                    <div class="ta-record-w">
                                        <div class="ta-record">
                                            <div class="ta-timestamp">
                                                <strong>9:32</strong> pm
                                            </div>
                                            <div class="ta-activity">Added
                                                <a href="#">John Silver</a> as a friend
                                            </div>
                                        </div>
                                        <div class="ta-record">
                                            <div class="ta-timestamp">
                                                <strong>5:14</strong> pm
                                            </div>
                                            <div class="ta-activity">Commented on story
                                                <a href="#">How to be a leader</a> in
                                                <a href="#">Financial</a> category
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="timed-activity">
                                    <div class="ta-date">
                                        <span>21st Jan, 2017</span>
                                    </div>
                                    <div class="ta-record-w">
                                        <div class="ta-record">
                                            <div class="ta-timestamp">
                                                <strong>11:55</strong> am
                                            </div>
                                            <div class="ta-activity">Created a post called
                                                <a href="#">Register new symbol</a> in Rogue
                                            </div>
                                        </div>
                                        <div class="ta-record">
                                            <div class="ta-timestamp">
                                                <strong>2:34</strong> pm
                                            </div>
                                            <div class="ta-activity">Commented on story
                                                <a href="#">How to be a leader</a> in
                                                <a href="#">Financial</a> category
                                            </div>
                                        </div>
                                        <div class="ta-record">
                                            <div class="ta-timestamp">
                                                <strong>9:39</strong> pm
                                            </div>
                                            <div class="ta-activity">Started following user
                                                <a href="#">Ben Mosley</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane" id="tab_conversion"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection