laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('form');
});
Route::post('submitForm','MuridController@indexDT');
Route::get('/downloadPDF/{id}','MuridController@downloadPDF');

Route::get('/', ['uses' => 'PresensiController@index', 'as' => 'presensi']);
Route::post('/presensi/post', ['uses' => 'PresensiController@presensi', 'as' => 'presensi-post']);
Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', ['uses' => 'IndexController@index', 'as' => 'dashboard']);


    Route::resource('riwayat', 'RiwayatController');
    Route::resource('murid', 'MuridController');
    Route::resource('kelas', 'KelasController');
    Route::resource('sesi-kelas', 'SesiKelasController');
    Route::resource('poin', 'PoinController');
    Route::get('bulk-add', 'MuridController@bulkAdd')->name('bulk');
    Route::post('bulk-add', 'MuridController@bulkAddPost')->name('bulk');
    Route::get('dt-murid', 'MuridController@indexDT')->name('dt-murid');
    Route::delete('/murid/{id}', 'MuridController@destroy')->name('murid.destroy');
    Route::delete('dl-murid', 'MuridController@destroy')->name('dl-murid');
    Route::get('murid/{id}/delete', ['uses' => 'MuridController@destroy', 'as' => 'murid.delete']);
    Route::get('dt-kelas', 'KelasController@kelasDT')->name('dt-kelas');
    Route::get('dt-riwayat', 'RiwayatController@kelasDT')->name('dt-riwayat');
    Route::get('r-murid', 'MuridController@rDT')->name('r-murid');
    Route::get('dt-sesi', 'SesiKelasController@sesiDT')->name('dt-sesi');
    Route::get('dt-poin-history/{id}', 'PoinController@poinHistoryDT')->name('dt-poin-history');
    Route::post('dz-upload', 'MuridController@dropZoneUpload')->name('dz-upload');
});

Route::get('Murid', function(MuridDataTable $dataTable) {
    return $dataTable->render('murid.index');
});


Route::get('debugging', function () {
    /* $date = \Carbon\Carbon::now()->setTimezone('Asia/Jakarta');
     $sesi = \App\SesiKelas::all();
     $now = $date->format('Y-m-d H:i:s');
     $day = $date->format('l');

     $output = array();
     foreach ($sesi as $sesi_kelas) {
         $start = \Carbon\Carbon::parse($sesi_kelas->jam_mulai)->format('Y-m-d H:i:s');
         $end = \Carbon\Carbon::parse($sesi_kelas->jam_selesai)->format('Y-m-d H:i:s');

         //cek sesi kelas
         if ($now > $start && $now < $end) {
             //cek murid sudah pernah absen pada sesi kelas
             $new_presensi = \App\Presensi::where('murid_id', '=', 22)->whereBetween('created_at', [$start, $end])->first();
             //dd($new_presensi->created_at);

             $presensi_exist_time = $new_presensi['created_at'];
             //dd($presensi_exist_time);
             if ($new_presensi !== null && $presensi_exist_time > $start && $presensi_exist_time < $end) {
                 $output = array();
                 $output = array(['type' => 'warning', 'message' => $new_presensi->murid->nama_lengkap . ' Telah melakukan presensi pada sesi kelas saat ini']);
             } else {

                 $output = array();
                 $output = array(['type' => 'success', 'message' => 'Berhasil melakukan presensi']);
                 break;
             }
         } else {
             $output = array(['type' => 'error', 'message' => 'Tidak ada kelas yg aktif pada saat ini']);
         }
     }
     return response()->json($output);*/
    $user = new \App\User();
    $user->name = 'Administrator';
    $user->username = 'administrator';
    $user->email = 'admin@presensi.com';
    $user->password = bcrypt('123456');
    $user->save();
    dd($user);

});
Auth::routes();

laravel/app/Presensi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Presensi
 *
 * @mixin \Eloquent
 * @property int $id
 * @property int $murid_id
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @property-read \App\Murid $murid
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Presensi whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Presensi whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Presensi whereMuridId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Presensi whereUpdatedAt($value)
 */
class Presensi extends Model
{
    protected $table = 'presensi';

    protected $fillable = ['murid_id'];

    public function murid()
    {
        return $this->belongsTo(Murid::class);
    }

}

laravel/app/Http/Controllers/PresensiController.php
<?php

namespace App\Http\Controllers;

use App\Murid;
use App\Poin;
use App\Presensi;
use App\SesiKelas;
use Carbon\Carbon;
use Illuminate\Http\Request;

class PresensiController extends Controller
{
    public function index()
    {
        return view('presensi.index');
    }

    public function presensi(Request $request)
    {
        $date = Carbon::now()->setTimezone('Asia/Jakarta');
        $sesi = SesiKelas::all();
        $now = $date->format('Y-m-d H:i:s');
        $day = $date->format('l');

        $output = array();
        foreach ($sesi as $sesi_kelas) {
            $start = Carbon::parse($sesi_kelas->jam_mulai)->format('Y-m-d H:i:s');
            $end = Carbon::parse($sesi_kelas->jam_selesai)->format('Y-m-d H:i:s');

            //cek sesi kelas
            if ($now > $start && $now < $end) {
                //cek murid sudah pernah absen pada sesi kelas
                $new_presensi = Presensi::where('murid_id', '=', $request->id)->whereBetween('created_at', [$start, $end])->first();
                $presensi_exist_time = $new_presensi['created_at'];
                //dd($presensi_exist_time);
                if ($new_presensi !== null && $presensi_exist_time > $start && $presensi_exist_time < $end) {
                    $output = array();
                    $output = array(['type' => 'warning', 'message' => $new_presensi->murid->nama_lengkap . ' Telah melakukan presensi pada sesi kelas saat ini']);
                } else {
                    $poin = new Poin();
                    $poin->poin = 1;
                    $poin->keterangan = 'Kehadiran';
                    $murid = Murid::find($request->id);
                    if ($murid->status_murid == 0) {
                        $hadir = $murid->presensi()->count();
                        if ($hadir > 3) {
                            $output = array();
                            $output = array(['type' => 'warning', 'message' => 'Kamu telah 3 kali hadir, silahkan mengisi data lengkap kamu <a href="' . route('murid.edit', $request->id) . '">disini</a>']);
                            break;
                        }
                    }
                    $murid->poin()->save($poin);
                    $presensi = new Presensi();
                    $presensi->murid()->associate($murid);
                    $presensi->save();
                    $output = array();
                    $output = array(['type' => 'success', 'message' => $murid->nama_lengkap . ' Berhasil melakukan presensi']);
                    break;
                }
            } else {
                $output = array(['type' => 'warning', 'message' => 'Tidak ada kelas yg aktif pada saat ini ']);
            }
        }
        return response()->json($output);

    }
}

laravel/resources/views/presensi/index.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>Presensi Member FOSSIL</title>
    <meta charset="utf-8">
    <meta content="ie=edge" http-equiv="x-ua-compatible">
    <meta content="template language" name="keywords">
    <meta content="TuxLabs" name="author">
    <meta content="Admin dashboard html template" name="description">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="favicon.png" rel="shortcut icon">
    <link href="apple-touch-icon.png" rel="apple-touch-icon">
    <link href="http://fast.fonts.net/cssapi/487b73f1-c2d1-43db-8526-db577e4c822b.css" rel="stylesheet" type="text/css">
    <link href="{{ asset('bower_components/select2/dist/css/select2.min.css') }}" rel="stylesheet">
    <link href="{{ asset('bower_components/boot') }}" rel="stylesheet">
    <link href="{{ asset('bower_components/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">
    <link href="{{ asset('bower_components/dropzone/dist/dropzone.css') }}" rel="stylesheet">
    <link href="{{ asset('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('bower_components/fullcalendar/dist/fullcalendar.min.css') }}" rel="stylesheet">
    <link href="{{ asset('bower_components/perfect-scrollbar/css/perfect-scrollbar.min.css') }}" rel="stylesheet">
    <link href="{{ asset('bower_components/slick-carousel/slick/slick.css') }}" rel="stylesheet">
    <link href="{{ asset('css/main9503.css?version=4.2.0') }}" rel="stylesheet">
    <style>
        #barcode-scanner video.drawingBuffer {
            display: none;
        }

        #barcode-scanner video {
            width: 100%;
            height: auto;
        }
    </style>
</head>

<body class="auth-wrapper">
<div class="all-wrapper menu-side with-pattern">
    <div class="auth-box-w">
        <div class="logo-w" style="padding: 5%;">
        </div>
        <h4 class="auth-header">Presensi</h4>
        <form action="#">
            <div class="form-group" style="margin-bottom: 0px">
                <label for="">ID Member</label>
                <input class="form-control" placeholder="ID Member" type="text" id="id-murid" name="id"
                       autocomplete="off">
                <div class="pre-icon os-icon os-icon-fingerprint"></div>
            </div>
            <small id="emailHelp" class="form-text text-muted"><a class="btn btn-link"
                                                                  href="{{ route('murid.create') }}">Tambah member
                    baru</a></small>
            <div class="row">
                <div id="interactive" class="form-control">
                    <video id="barcode-scanner" width="100%" height="auto"></video>
                </div>
            </div>
        </form>

    </div>
</div>
<script src="{{ asset('bower_components/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ asset('bower_components/quagga/quagga.js') }}"></script>
<script src="{{ asset('js/instascan.min.js') }}"></script>
<script src="{{ asset('js/sweetalert2.all.js') }}"></script>
<script>
    $(function () {
        $('#id-murid').keypress(function (e) {
            if (e.which === 13) {
                e.preventDefault();
                var id_murid = $(this).val();
                new_presensi(id_murid);
            }
        });
        var new_presensi = function (content) {
            $.ajax({
                url: '{{ route('presensi-post') }}',
                type: 'POST',
                data: {
                    id: content,
                    _token: '{{ csrf_token() }}'
                },
                dataType: 'json',
                success: function (result) {
                    console.log(result);
                    //var json = $.parseJSON(result[0]);
                    swal({
                        type: result[0].type,
                        title: result[0].message,
                        showConfirmButton: true,

                    });

                }
            });
        };
        const scanner = new Instascan.Scanner({video: document.getElementById('barcode-scanner')});
        scanner.addListener('scan', function (content) {
            if (content == null) {
                console.log('no barcode')
            } else {
                new_presensi(content)
                //alert(content);
            }

        });
        Instascan.Camera.getCameras().then(function (cameras) {
            if (cameras.length > 0) {
                scanner.start(cameras[0]);
            } else {
                console.error('No cameras found.');
            }
        }).catch(function (e) {
            console.error(e);
        });
    });


    /*var w = window.innerWidth;

    var h = window.innerHeight;

    Quagga.init({
        inputStream: {
            name: "Live",
            type: "LiveStream",
            target: document.querySelector('#barcode-scanner')    // Or '#yourElement' (optional)

        },

        decoder: {
            readers: ["code_128_reader",
                "ean_reader",
                "ean_8_reader",
                "code_39_reader",
                "code_39_vin_reader",
                "codabar_reader",
                "upc_reader",
                "upc_e_reader",
                "i2of5_reader"]
        }
    }, function (err) {
        if (err) {
            console.log(err);
            return
        }
        console.log("Initialization finished. Ready to start");
        Quagga.start();
    });
    Quagga.onDetected(function (result) {
        alert("Barcode detected and processed : [" + result.codeResult.code + "]");
        $('#id-murid').val(result.codeResult.code)
    });*/
</script>
</body>

</html>