laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('form');
});
Route::post('submitForm','MuridController@indexDT');
Route::get('/downloadPDF/{id}','MuridController@downloadPDF');

Route::get('/', ['uses' => 'PresensiController@index', 'as' => 'presensi']);
Route::post('/presensi/post', ['uses' => 'PresensiController@presensi', 'as' => 'presensi-post']);
Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', ['uses' => 'IndexController@index', 'as' => 'dashboard']);


    Route::resource('riwayat', 'RiwayatController');
    Route::resource('murid', 'MuridController');
    Route::resource('kelas', 'KelasController');
    Route::resource('sesi-kelas', 'SesiKelasController');
    Route::resource('poin', 'PoinController');
    Route::get('bulk-add', 'MuridController@bulkAdd')->name('bulk');
    Route::post('bulk-add', 'MuridController@bulkAddPost')->name('bulk');
    Route::get('dt-murid', 'MuridController@indexDT')->name('dt-murid');
    Route::delete('/murid/{id}', 'MuridController@destroy')->name('murid.destroy');
    Route::delete('dl-murid', 'MuridController@destroy')->name('dl-murid');
    Route::get('murid/{id}/delete', ['uses' => 'MuridController@destroy', 'as' => 'murid.delete']);
    Route::get('dt-kelas', 'KelasController@kelasDT')->name('dt-kelas');
    Route::get('dt-riwayat', 'RiwayatController@kelasDT')->name('dt-riwayat');
    Route::get('r-murid', 'MuridController@rDT')->name('r-murid');
    Route::get('dt-sesi', 'SesiKelasController@sesiDT')->name('dt-sesi');
    Route::get('dt-poin-history/{id}', 'PoinController@poinHistoryDT')->name('dt-poin-history');
    Route::post('dz-upload', 'MuridController@dropZoneUpload')->name('dz-upload');
});

Route::get('Murid', function(MuridDataTable $dataTable) {
    return $dataTable->render('murid.index');
});


Route::get('debugging', function () {
    /* $date = \Carbon\Carbon::now()->setTimezone('Asia/Jakarta');
     $sesi = \App\SesiKelas::all();
     $now = $date->format('Y-m-d H:i:s');
     $day = $date->format('l');

     $output = array();
     foreach ($sesi as $sesi_kelas) {
         $start = \Carbon\Carbon::parse($sesi_kelas->jam_mulai)->format('Y-m-d H:i:s');
         $end = \Carbon\Carbon::parse($sesi_kelas->jam_selesai)->format('Y-m-d H:i:s');

         //cek sesi kelas
         if ($now > $start && $now < $end) {
             //cek murid sudah pernah absen pada sesi kelas
             $new_presensi = \App\Presensi::where('murid_id', '=', 22)->whereBetween('created_at', [$start, $end])->first();
             //dd($new_presensi->created_at);

             $presensi_exist_time = $new_presensi['created_at'];
             //dd($presensi_exist_time);
             if ($new_presensi !== null && $presensi_exist_time > $start && $presensi_exist_time < $end) {
                 $output = array();
                 $output = array(['type' => 'warning', 'message' => $new_presensi->murid->nama_lengkap . ' Telah melakukan presensi pada sesi kelas saat ini']);
             } else {

                 $output = array();
                 $output = array(['type' => 'success', 'message' => 'Berhasil melakukan presensi']);
                 break;
             }
         } else {
             $output = array(['type' => 'error', 'message' => 'Tidak ada kelas yg aktif pada saat ini']);
         }
     }
     return response()->json($output);*/
    $user = new \App\User();
    $user->name = 'Administrator';
    $user->username = 'administrator';
    $user->email = 'admin@presensi.com';
    $user->password = bcrypt('123456');
    $user->save();
    dd($user);

});
Auth::routes();

laravel/app/Murid.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Murid
 *
 * @mixin \Eloquent
 * @property int $id
 * @property string $murid_id
 * @property string $nama_lengkap
 * @property string $gender
 * @property string|null $nama_panggilan
 * @property string $tempat_lahir
 * @property string $tanggal_lahir
 * @property string|null $alamat
 * @property string|null $no_telepon
 * @property int $kelas_id
 * @property int $status_murid
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @property-read \App\Kelas $kelas
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Murid whereAlamat($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Murid whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Murid whereGender($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Murid whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Murid whereKelasId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Murid whereNamaLengkap($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Murid whereNamaPanggilan($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Murid whereNoTelepon($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Murid whereUpdatedAt($value)
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Poin[] $poin
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Presensi[] $presensi
 */
class Murid extends Model
{
    protected $table = 'murid';
    protected $fillable = ['murid_id', 'nama_lengkap', 'gender', 'nama_panggilan','nim','kelas_mhs',  'alamat', 'no_telepon', 'kelas_id', 'status_murid', 'foto'];

    public function kelas()
    {
        return $this->belongsTo(Kelas::class);
    }

    public function poin()
    {
        return $this->hasMany(Poin::class);
    }

    public function presensi()
    {
        return $this->hasMany(Presensi::class);
    }


}

laravel/app/Http/Controllers/MuridController.php
<?php

namespace App\Http\Controllers;

use App\Kelas;
use App\Murid;
// use App\Poin;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Yajra\DataTables\Exceptions\Exception;
use App\DataTables\UsersDataTable;
use PDF;

class MuridController extends Controller
{
    // tambahan
    // public function index(UsersDataTable $dataTable)
    // {
    //     return $dataTable->render('murid');
    // }

    // tambahan
    public function downloadPDF($id){
        $murid = Murid::find($id);
  
        $pdf = PDF::loadView('pdf', compact('murid'));
        return $pdf->download('invoice.pdf');
  
      }

    public function bulkAdd()
    {
        $kelas = Kelas::all();
        return view('bulk.create', compact('kelas'));
    }

    public function bulkAddPost(Request $request)
    {
        for ($i = 0; $i < $request->jumlah; $i++) {
            $murid = new Murid();
            $murid->nama_lengkap = 'Murid Baru';
            $murid->gender = 'N';
            $murid->nim = '18.xx.xxx';
            $murid->kelas_mhs = '18-xxxx-xx';
            $murid->nama_panggilan = 'Nama Panggilan';
            $murid->no_telepon = '00';
            $murid->alamat = 'Alamat Member';
            $kelas = Kelas::find($request->kelas);
            $murid->kelas()->associate($kelas);
            $save = $murid->save();
        }


        return redirect()->route('murid.index');
    }

    public function indexDT()
    {
        $murid = Murid::query();
        try {
            $dt = DataTables::of($murid)
                ->addColumn('action', function ($res) {
                    return '<input type="hidden" id="murid-id" value="' . $res->id . '"><a href="' . route('murid.show', $res->id) . '" class="btn btn-outline-primary btn-sm"><i class="os-icon os-icon-edit-3"></i></a>';
                })
                ->editColumn('kelas_id', function ($res) {
                    return strtoupper($res->kelas->nama_kelas);
                })
                ->editColumn('gender', function ($res) {
                    if ($res->gender == 'L')
                        return 'LAKI-LAKI';
                    else
                        return 'PEREMPUAN';
                })
                ->editColumn('tanggal_lahir', function ($res) {
                    return Carbon::parse($res->tanggal_lahir)->age;
                })
                ->removeColumn('tempat_lahir', 'alamat', 'no_telepon', 'foto' , 'created_at', 'updated_at')
                ->make(true);
        } catch (\Exception $exception) {
            return $exception;
        }
        return $dt;
    }

    public function dropZoneUpload(Request $request)
    {
        //dd($request->file('file'));
        if ($request->hasFile('file')) {
            $path = $request->file('file')->store('storage/img/foto-murid', 'public');
        }
        return response()->json($path);

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //dd($this->indexDT());

        // return $dataTable->render('murid.index');

        return view('murid.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kelas = Kelas::all();
        return view('murid.create', compact('kelas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $murid = new Murid();
        $murid->id = $request->id;
        $murid->murid_id = $request->murid_id;
        $murid->nama_lengkap = $request->nama_lengkap;
        $murid->gender = $request->gender;
        $murid->nim = $request->nim;
        $murid->kelas_mhs = $request->kelas_mhs;
        $murid->nama_panggilan = $request->nama_panggilan;
        $murid->no_telepon = $request->no_telepon1 . ',' . $request->no_telepon2;
        $murid->alamat = $request->alamat;
        $murid->foto = $request->foto;
        $kelas = Kelas::find($request->kelas);
        $murid->kelas()->associate($kelas);
        $save = $murid->save();

        return redirect()->route('murid.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $murid = Murid::find($id);
        return view('murid.show', compact('murid'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $murid = Murid::find($id);
        $kelas = Kelas::all();
        return view('murid.edit', compact('murid', 'kelas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $murid = Murid::find($id);
        $murid->id = $request->id;
        $murid->murid_id = $request->murid_id;
        $murid->nama_lengkap = $request->nama_lengkap;
        $murid->gender = $request->gender;
        $murid->nim = $request->nim;
        $murid->kelas_mhs = $request->kelas_mhs;
        $murid->nama_panggilan = $request->nama_panggilan;
        $murid->no_telepon = $request->no_telepon1 . ',' . $request->no_telepon2;
        $murid->alamat = $request->alamat;
        if (isset($request->foto)) {
            $murid->foto = $request->foto;
        }
        $kelas = Kelas::find($request->kelas);
        $murid->kelas()->associate($kelas);
        $save = $murid->save();
        return redirect()->route('murid.index', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $murid =  Murid::findOrFail($id)->delete();
        // Session::flash('Item successfully deleted');
        return redirect('murid');
    
   
        //
    }

    public function xx(Request $request)
    {
        // $poin = new Poin([
        //     'poin' => 1,
        //     'keterangan' => $request->keterangan
        // ]);
        // $murid = Murid::find($request->murid_id);
        // $murid->poin()->save($poin);
        //  $murid =  Murid::findOrFail($id)->delete();
        // return redirect()->back();
    }
}

laravel/resources/views/murid/_form.blade.php
<h5 class="form-header">Data Member</h5>
<div class="form-desc">Form dengan tanda <span class="text-danger">*</span> harus di isi.
</div>
<div class="form-group">
    <label for=""> ID Member </label>
    <input class="form-control" data-error="ID harus di isi"
           placeholder="Masukkan ID Member" name="id" type="text"
           value="{{ @$murid->id }}">
    <div class="help-block form-text with-errors form-control-feedback"></div>
</div>
<div class="form-group">
    <label for=""> NIM </label>
    <input class="form-control" data-error="NIM harus di isi"
           placeholder="Masukkan Nomor Induk Mahasiswa" name="nim" type="text"
           value="{{ @$murid->nim }}">
    <div class="help-block form-text with-errors form-control-feedback"></div>
</div>
<div class="form-group">
    <label for=""> Kelas </label>
    <input class="form-control" data-error="Kelas harus di isi"
           placeholder="Masukkan Kelas Mahasiswa" name="kelas_mhs" type="text"
           value="{{ @$murid->kelas_mhs }}">
    <div class="help-block form-text with-errors form-control-feedback"></div>
</div>
<div class="form-group">
    <label for=""> Nama Lengkap <span class="text-danger">*</span></label>
    <input class="form-control" data-error="Nama harus di isi"
           placeholder="Masukkan nama lengkap" required="required" name="nama_lengkap" type="text"
           value="{{ @$murid->nama_lengkap }}">
    <div class="help-block form-text with-errors form-control-feedback"></div>
</div>
<div class="form-group">
    <label for=""> Nama Panggilan</label>
    <input class="form-control" data-error="Nama harus di isi"
           placeholder="Masukkan nama panggilan" name="nama_panggilan" type="text"
           value="{{ @$murid->nama_panggilan }}">
    <div class="help-block form-text with-errors form-control-feedback"></div>
</div>
<div class="form-group">
    <label for=""> Gender <span class="text-danger">*</span></label>
    <select class="form-control" required="required" name="gender">
        <option value="L">Laki-laki</option>
        <option value="P">Perempuan</option>
    </select>
</div>

<div class="form-group">
    <label for=""> Kelas <span class="text-danger">*</span></label>
    <select class="form-control" required="required" name="kelas">
        @foreach($kelas as $item)
            <option value="{{ $item->id }}">{{ $item->nama_kelas }}</option>
        @endforeach
    </select>
</div>

<fieldset class="form-group">
    <legend>
        <span>Kontak</span>
    </legend>
    <!-- <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label for=""> Nama Ayah</label>
                <input class="form-control" data-error="Isi nama ayah"
                       placeholder="Masukkan nama ayah" type="text" name="nama_ayah" value="{{ @$murid->nama_ayah }}">
                <div class="help-block form-text with-errors form-control-feedback"></div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label for="">Nama Ibu</label>
                <input class="form-control"
                       placeholder="Nama Ibu" type="text" name="nama_ibu" value="{{ @$murid->nama_ibu }}">
                <div class="help-block form-text with-errors form-control-feedback"></div>
            </div>
        </div>
    </div> -->
</fieldset>
@php($telp = explode(',',@$murid->no_telepon))
<div class="row">
    <div class="col-sm-6">
        <div class="form-group">
            <label for=""> Nomor Telepon</label>
            <input class="form-control"
                   placeholder="Masukkan nomor telepon" type="text" name="no_telepon1" value="{{ @$telp[0] }}">
            <div class="help-block form-text with-errors form-control-feedback"></div>
        </div>
    </div>
    <!-- <div class="col-sm-6">
        <div class="form-group">
            <label for=""> Nomor Telepon 2</label>
            <input class="form-control"
                   placeholder="Masukkan nomor telepon" type="text" name="no_telepon2" value="{{ @$telp[1] }}">
            <div class="help-block form-text with-errors form-control-feedback"></div>
        </div>
    </div> -->
</div>
<div class="form-group">
    <label> Alamat</label>
    <textarea class="form-control" rows="3" name="alamat">{{ @$murid->alamat }}</textarea>
</div>
<fieldset class="form-group">
    <legend>
        <span>Foto</span>
    </legend>
    <div class="form-group" id="dz-upload">
        <div class="dz-message">
            <div>
                <h4>Drop files here or click to upload.</h4>

            </div>
        </div>
    </div>
    <input type="hidden" name="foto" id="foto">
</fieldset>
{{ csrf_field() }}
<div class="form-buttons-w">
    <button class="btn btn-primary" type="submit"> Submit</button>
</div>

laravel/resources/views/murid/create.blade.php
@extends('layout.master')

@section('title')
    <title>Tambah Member - Admin</title>
@stop

@section('content-box')
    <div class="row">
        <div class="col-sm-12">
            <div class="element-wrapper">
                <div class="element-box">
                    <form id="formValidate" method="post" action="{{ route('murid.store') }}">
                        @include('murid._form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('content-panel')
    <div class="content-panel">

    </div>
@endsection

@section('script')
    <script>
        $(function () {
            $('div#dz-upload').addClass('dropzone').dropzone({
                url: "{{ route('dz-upload') }}",
                method: "post",
                uploadMultiple: false,
                maxFiles: 1,
                acceptedFiles: "image/*",
                init: function () {
                    var myDropzone = this;
                    this.on("sending", function (file, xhr, formData) {
                        formData.append("_token", '{{ csrf_token() }}');
                    });
                    this.on("success", function (files, response) {

                        $('#foto').val(response);
                        console.log(response);
                    });

                }
            })
        });

    </script>
@endsection

laravel/resources/views/murid/edit.blade.php
@extends('layout.master')

@section('title')
    <title>Edit {{ ucwords(strtolower($murid->nama_lengkap)) }} - Member</title>
@stop

@section('content-box')
    <div class="row">
        <div class="col-sm-12">
            <div class="element-wrapper">
                <div class="element-box">
                    <form id="formValidate" method="post" action="{{ route('murid.update', $murid->id) }}">
                        @include('murid._form')
                        {{ method_field('PUT') }}
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('content-panel')
    <div class="content-panel">

    </div>
@endsection

@section('script')
    <script>
        $(function () {
            $('div#dz-upload').addClass('dropzone').dropzone({
                url: "{{ route('dz-upload') }}",
                method: "post",
                uploadMultiple: false,
                maxFiles: 1,
                acceptedFiles: "image/*",
                init: function () {
                    var myDropzone = this;
                    var mockFile = {name: "Filename", size: 0};
                    myDropzone.emit("addedfile", mockFile);
                    myDropzone.emit("thumbnail", mockFile, "{{ asset('storage/'.@$murid->foto) }}");
                    myDropzone.files.push(mockFile);
                    myDropzone.emit("complete", mockFile);
                    console.log(myDropzone.files.length);
                    this.on("sending", function (file, xhr, formData) {
                        formData.append("_token", '{{ csrf_token() }}');
                    });
                    this.on("success", function (files, response) {
                        this.removeFile(mockFile);
                        $('#foto').val(response);
                        console.log(response);
                    });

                }
            })
        });

    </script>
@endsection

laravel/resources/views/murid/index.blade.php
@extends('layout.master')

@section('title')
    <title>Daftar Member - Admin</title>
@stop

@section('content-box')
    <div class="element-wrapper">
        <h6 class="element-header">Member</h6>
        <div class="element-box">
            <h5 class="form-header">Daftar Member</h5>
            <div class="form-desc">Berisi data member FOSSIL
            </div>
            <div class="controls-above-table">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-inline justify-content-sm-end">
                            <a class="btn btn-primary" href="{{ route('murid.create') }}">Tambah</a>
                            
                          
                        </div>
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table id="tabel-murid" width="100%" class="table table-hover table-striped table-lightfont">
                    <thead>
                    <tr>
                        <th>Member ID</th>
                        <th>Nama</th>
                        <th>Nama Panggilan</th>
                        <th>Gender</th>
                        <th>Kelas</th>
                        <th>Divisi</th>
                        <th>Edit</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Member ID</th>
                        <th>Nama</th>
                        <th>Nama Panggilan</th>
                        <th>Gender</th>
                        <th>Kelas</th>
                        <th>Divisi</th>
                        <th>Edit</th>
                    </tr>
                    </tfoot>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('script')
<!-- <div aria-labelledby="exampleModalLabel" class="modal fade" id="exampleModal1" role="dialog"
         tabindex="-1" aria-hidden="true" data-backdrop="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header"><h5 class="modal-title" id="exampleModalLabel">Hapus Data</h5>
                    <button aria-label="Close" class="close" data-dismiss="modal" type="button"><span
                                aria-hidden="true"> ×</span></button>
                </div>
                <form method="post">
                    <div class="modal-body">

                       
                        <input type="hidden" name="murid_id" value="" id="id">
                        {!! method_field('delete') !!}
                         {!! csrf_field() !!}    

                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" data-dismiss="modal"> Batal</button>
                        <button class="btn btn-primary" type="submit" > Hapus</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div aria-labelledby="exampleModalLabel" class="modal fade" id="exampleModal1" role="dialog"
         tabindex="-1" aria-hidden="true" data-backdrop="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header"><h5 class="modal-title" id="exampleModalLabel">Tambah Poin</h5>
                    <button aria-label="Close" class="close" data-dismiss="modal" type="button"><span
                                aria-hidden="true"> ×</span></button>
                </div>
                <form method="post" action="{{ route('dt-murid') }}">
                    <div class="modal-body">

                        <div class="form-group"><label for=""> Keterangan</label><input
                                    class="form-control" placeholder="Keterangan" name="keterangan" type="text"></div>
                        <input type="hidden" name="murid_id" value="" id="id">
                        {{ csrf_field() }}

                    </div>
                    <div class="modal-footer">
                    <button class="btn btn-secondary" data-dismiss="modal"> Batal</button>
                        <button class="btn btn-primary" type="submit" > Hapus</button>
                    </div>
                </form>
            </div>
        </div>
    </div> -->
    <script>
        $(function () {
            $('#tabel-murid').css('text-transform', 'capitalize').DataTable({
                pagingType: "simple_numbers",
                dom: 'Bfrtip',
                paging: true,
                pageLength: 25,
                order: [[0, "asc"]],
                processing: true,
                serverSide: true,
                ajax: '{{ route('dt-murid') }}',
                // tambahan
                buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
                ],
                // tambahan
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'nama_lengkap', name: 'nama_lengkap'},
                    {data: 'nama_panggilan', name: 'nama_panggilan'},
                    {data: 'gender', name: 'gender'},
                    {data: 'kelas_mhs', name: 'kelas_mhs'},
                    {data: 'kelas_id', name: 'kelas_id', searchable: true},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ]
            });
            $(document).on('click',  function (e) {
                var murid_id = $(this).closest('td').find('#murid-id').val();
                $('#id').val(murid_id);
                $('#exampleModal1').modal();
                $.ajax({
                    url: url,
                    type: 'DELETE',
                    dataType: 'json',
                    data: {method: '_DELETE', submit: true}
                }).always(function (data) {
                    $('#murid-d').DataTable().draw(false);
                });

            })
        });

    </script>

    <script>
    $(function () {
        $('#export-table').DataTable({
            pagingType: "simple_numbers",
            dom: 'Bfrtip',
            paging: true,
            pageLength: 25,
            order: [[0, "asc"]],
            processing: true,
            serverSide: true,
            responsive: true,
            autoWidth:false,
            aaSorting: [[6, 'desc']],
            ajax: '{!! route('dt-murid') !!}',
            buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
            ],
            aoColumns: [
                {data: 'id', name: 'id'},
                {data: 'nama_lengkap', name: 'nama_lengkap'},
                {data: 'nama_panggilan', name: 'nama_panggilan'},
                {data: 'gender', name: 'gender'},
                {data: 'kelas_mhs', name: 'kelas_mhs'},
                {data: 'kelas_id', name: 'kelas_id', searchable: true},
                {mData:'action', name: 'action'}
            ],
           
        });
    });

    </script>
   
   <!-- <script src="//code.jquery.com/jquery.js"></script>
   <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.0.3/css/buttons.dataTables.min.css">
    <script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script> 
    <script src="/vendor/datatables/buttons.server-side.js"></script> -->

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js"></script>
 

    
 
@endsection